// generated by: npx docusaurus swizzle @docusaurus/theme-classic NavbarItem --wrap
// https://docusaurus.io/docs/swizzling

import React from "react";
import NavbarItem from "@theme-original/NavbarItem";
import type NavbarItemType from "@theme/NavbarItem";
import type { WrapperProps } from "@docusaurus/types";
import ContextualVersionDropdown from "@site/src/components/ContextualVersionDropdown";
import SidebarDropdownNavbarItem from "@site/src/components/SidebarDropdownNavbarItem";

// @ts-ignore ReactNode is not assignable to ReactElement
// Docusaurs uses ReactNode, which breaks the type compatibility
type Props = WrapperProps<typeof NavbarItemType>;

export default function NavbarItemWrapper(
  props: Props & { type?: string; items?: any },
) {
  // Handle our custom version dropdown type
  if (props.type === "custom-contextualVersionDropdown") {
    return <ContextualVersionDropdown />;
  }

  // Handle our custom sidebar dropdown type
  if (props.type === "custom-sidebarDropdownNavbarItem" && props.items) {
    return <SidebarDropdownNavbarItem items={props.items} />;
  }

  // For all other types, use the original NavbarItem component
  return (
    <>
      <NavbarItem {...props} />
    </>
  );
}
